### ISSUE TITLE
trigger_push/trigger_once/point_teleport errors

### ISSUE THREAD

**Issue by testingh6** [H2xDev/GodotVMF-Project-Template#1]
got some issues in a vmf with these entities

**trigger_push.gd**
"line 22 	var is_character_body = node is CharacterBody3D and node.has_flag(FLAG_CLIENTS);"

invalid call. nonexistent function "has_flag" in base characterbody3d (player)

**trigger_once** doesnt fire any outputs when entered 

**point_teleport.gd** on line 6
Invalid assignment of property or key "global_transform" with value of type "Transform3D" on a base object of type "null instance"

**Comment by H2xDev** [comment]
@testingh6 

Hello! Sorry for late answer.
I made a fix, please check this branch - [bugfix/1](https://github.com/H2xDev/GodotVMF-Project-Template/tree/bugfix/1)

**Comment by testingh6** [comment]
¯\_(ツ)_/¯

**Comment by H2xDev** [comment]
@testingh6 
> ¯_(ツ)_/¯

How should i identify this answer? :)

**Comment by yours554** [comment]
these arent working for me either, clients is checked on all them, i run into triggeronce and trigger push and no output. for point teleport i put on the trigger_multiple  OnStartTouch:Des_01:Teleport
Des_01:Entity_to_telport:Player
